jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./lambda/pytorch.sh
         ./lambda/pytorch.sh
      shell: bash